name: Auto Release on Windows

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Generate version
        id: version
        shell: bash
        run: |
          latest=$(git tag | sort -V | tail -n1)
          echo "Latest tag: $latest"
          if [[ "$latest" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            patch=$((patch + 1))
            new="v$major.$minor.$patch"
          else
            new="v1.0.0"
          fi
          echo "New version: $new"
          echo "version=$new" >> $GITHUB_OUTPUT

      - name: Set Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Create Git tag
        run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}

      - name: Build zip (example)
        run: Compress-Archive -Path .\src\* -DestinationPath build\output.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: |
            build/output.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
