name: Auto Release on Windows

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Code Path
        run: dir

      - name: Build Go
        run: go build -o ./build/sentrigo.exe ./cmd/sentrigo/

      - name: Test Output Path
        run: dir build
